baseURL = 'https://patzsche.de'
languageCode = 'en-us'
title = 'patzsche.de'
theme = 'ananke'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3

[params]
    site_logo = "img/logo_white_123px.svg"
    description = "Some of my thoughts may be found here."
    author = "patzsche"

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[[params.ananke_socials]]
    name = "github"
    url = "https://github.com/Zehamor368"
    color = "#ffffff"
    rel = "noopener"
